name: Build and Release Kernel

on:
  workflow_dispatch:

jobs:
  Kernel:
    runs-on: ubuntu-latest
    defaults:
      run:
       shell: bash
       working-directory: ${{ github.workspace }}

    steps:
      - name: Cleanup
        run: rm -rf ${{ github.workspace }}/*

      - name: Set-up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev
          sudo apt-get install -y curl git ftp lftp wget libarchive-tools ccache python2 python2-dev
          sudo apt-get install -y zip unzip tar gzip bzip2 rar unrar cpio jq

      - name: Clone kernel source
        run: git clone https://github.com/dogpoopy/android_kernel_xiaomi_vayu.git -b main --depth=1 .

      - name: Start Compilation
        run: bash build.sh

      - name: Set-up files
        run: |
          # Set-up files info
            zip_file=$(find $HOME -name 'Hiraya*.zip' -print -quit)
            echo "ZIP_FILE=$zip_file" >> $GITHUB_ENV
            echo "ZIP_NAME=$(basename "$zip_file" .zip)" >> $GITHUB_ENV

      - name: Upload files to repository releases page
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ZIP_FILE }}
          name: ${{ env.ZIP_NAME }}
          tag_name: ${{ github.run_id }}
          body: |
            Not KernelSU
